# Generated by Django 4.2.6 on 2023-10-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='contactinfo/')),
                ('name', models.CharField(max_length=256)),
                ('short_description', models.CharField(max_length=256)),
                ('article_title', models.CharField(max_length=256)),
                ('article_content', models.TextField()),
                ('twitter_url', models.CharField(max_length=256)),
                ('facebook_url', models.CharField(max_length=256)),
                ('linkedin_url', models.CharField(max_length=256)),
                ('instagram_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
            ],
        ),
    ]
